// Fictional catalog for the test shop. All titles are made up.
window.GAMES = [
  { id: 1,  title: "Nebula Drifters",     genre: "Space",      price: 29.99, sale: null,  rating: 4.6, year: 2025, icon: "🚀", colors: ["#1b1464", "#7b2ff7"], platforms: ["PC", "PS5"],            desc: "Pilot a salvaged freighter across a dying galaxy. Trade, smuggle and fight your way to the Core." },
  { id: 2,  title: "Crimson Keep",        genre: "RPG",        price: 39.99, sale: 29.99, rating: 4.8, year: 2024, icon: "🏰", colors: ["#5c0a0a", "#d63031"], platforms: ["PC", "Xbox", "PS5"],    desc: "A 60-hour dark fantasy epic. Reclaim a cursed castle, one haunted wing at a time." },
  { id: 3,  title: "Turbo Tadpoles",      genre: "Racing",     price: 14.99, sale: null,  rating: 4.1, year: 2023, icon: "🐸", colors: ["#0b6e4f", "#7bed9f"], platforms: ["PC", "Switch"],        desc: "Arcade kart racing, but you are a tadpole and the track is a very wet pond." },
  { id: 4,  title: "Quantum Chef",        genre: "Puzzle",     price: 9.99,  sale: 4.99,  rating: 4.4, year: 2024, icon: "🍳", colors: ["#e17055", "#fdcb6e"], platforms: ["PC", "Switch", "Mobile"], desc: "Cook in a kitchen where the ingredients exist in two places at once. Michelin stars not guaranteed." },
  { id: 5,  title: "Iron Meridian",       genre: "Strategy",   price: 34.99, sale: null,  rating: 4.5, year: 2025, icon: "⚙️", colors: ["#2d3436", "#74b9ff"], platforms: ["PC"],                   desc: "Build a steampunk empire along a single endless railway. Turn-based, brutally fair." },
  { id: 6,  title: "Pixel Pirates",       genre: "Adventure",  price: 19.99, sale: null,  rating: 4.2, year: 2022, icon: "🏴‍☠️", colors: ["#0984e3", "#00cec9"], platforms: ["PC", "Switch"],        desc: "A retro pixel-art adventure on the high seas. Plunder islands, befriend parrots." },
  { id: 7,  title: "Shadow Protocol",     genre: "Shooter",    price: 49.99, sale: 39.99, rating: 4.0, year: 2025, icon: "🎯", colors: ["#111", "#636e72"],    platforms: ["PC", "Xbox", "PS5"],    desc: "Tactical stealth shooter. One mistake and the whole building knows." },
  { id: 8,  title: "Mochi Mountain",      genre: "Cozy",       price: 12.99, sale: null,  rating: 4.9, year: 2024, icon: "🍡", colors: ["#fd79a8", "#ffeaa7"], platforms: ["PC", "Switch", "Mobile"], desc: "Run a tiny dumpling shop on a sleepy mountain. No timers, no stress, lots of tea." },
  { id: 9,  title: "Void Hunters",        genre: "Shooter",    price: 24.99, sale: null,  rating: 4.3, year: 2023, icon: "👾", colors: ["#2c0a4a", "#00b894"], platforms: ["PC", "PS5"],           desc: "Co-op bullet-heaven for up to four players. The void has teeth." },
  { id: 10, title: "Dungeon Dispatch",    genre: "RPG",        price: 17.99, sale: 11.99, rating: 4.5, year: 2023, icon: "🗝️", colors: ["#3d2b1f", "#e1b12c"], platforms: ["PC", "Mobile"],        desc: "You don't fight the dungeon — you deliver packages through it. Tips are lava-proof." },
  { id: 11, title: "Skyline Skaters",     genre: "Sports",     price: 27.99, sale: null,  rating: 3.9, year: 2024, icon: "🛹", colors: ["#fab1a0", "#0984e3"], platforms: ["PC", "Xbox", "Switch"], desc: "Grind rooftops, bail spectacularly, and unlock a city built for kickflips." },
  { id: 12, title: "Echoes of Atlantis",  genre: "Adventure",  price: 32.99, sale: null,  rating: 4.7, year: 2025, icon: "🔱", colors: ["#006266", "#1289a7"], platforms: ["PC", "PS5"],           desc: "Dive into a sunken city and piece together its story from whispered echoes." },
  { id: 13, title: "Brick Breaker Galaxy",genre: "Puzzle",     price: 6.99,  sale: null,  rating: 4.0, year: 2021, icon: "🧱", colors: ["#ee5a24", "#f79f1f"], platforms: ["PC", "Mobile"],        desc: "Classic brick-breaking, reimagined with gravity wells and exploding comets." },
  { id: 14, title: "Last Light Outpost",  genre: "Strategy",   price: 21.99, sale: 14.99, rating: 4.6, year: 2024, icon: "🔦", colors: ["#192a56", "#fbc531"], platforms: ["PC", "Switch"],        desc: "Defend a lone lighthouse against the encroaching fog. Tower defense with heart." },
  { id: 15, title: "Rally Rhino",         genre: "Racing",     price: 19.99, sale: null,  rating: 3.8, year: 2022, icon: "🦏", colors: ["#576574", "#c8d6e5"], platforms: ["PC", "Xbox"],          desc: "Off-road racing with a very determined rhinoceros. Steering is optional." },
  { id: 16, title: "Clockwork Garden",    genre: "Cozy",       price: 15.99, sale: null,  rating: 4.8, year: 2025, icon: "🌻", colors: ["#009432", "#c4e538"], platforms: ["PC", "Switch", "Mobile"], desc: "Grow mechanical flowers in a garden that ticks. Relaxing, strange, beautiful." }
];
